<a href="https://colab.research.google.com/github/SinghAbh1shek/Pandas/blob/main/Pandas_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
customers_data = pd.read_excel('/content/customers_lyst1748071473851.xlsx')
products_data = pd.read_excel('/content/products_lyst1748071481613.xlsx')
purchases_data = pd.read_excel('/content/purchases_lyst1748071489995.xlsx')

In [ ]:
customers_data.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

In [ ]:
products_data.head()

   Unnamed: 0  id                           product    cost   company
0           0   1              Liners - Baking Cups   $6.36  Skipfire
1           1   2        Nori Sea Weed - Gold Label  $85.74   Dynazzy
2           2   3                Bar Bran Honey Nut  $65.40      Ntag
3           3   4        Soup - Campbells Beef Stew  $68.16  Photojam
4           4   5  Wine - Shiraz Wolf Blass Premium  $87.39      Eare

In [ ]:
products_data.drop(columns=['Unnamed: 0'], inplace=True)
products_data.head()

   id                           product    cost   company
0   1              Liners - Baking Cups   $6.36  Skipfire
1   2        Nori Sea Weed - Gold Label  $85.74   Dynazzy
2   3                Bar Bran Honey Nut  $65.40      Ntag
3   4        Soup - Campbells Beef Stew  $68.16  Photojam
4   5  Wine - Shiraz Wolf Blass Premium  $87.39      Eare

In [ ]:
purchases_data.head()

,Unnamed: 0,id,purch_date,customer_num,product_num,amount,paid
0,0,1,2019-01-03 00:00:00,823,27,12,$568.92
1,1,2,2019-01-03 00:00:00,606,28,14,$395.36
2,2,3,2019-01-03 00:00:00,955,9,17,$510.17
3,3,4,2019-01-03 00:00:00,577,19,3,$68.49
4,4,5,2019-01-03 00:00:00,429,8,18,$759.42

In [ ]:
purchases_data.drop(columns=['Unnamed: 0'], inplace=True)
purchases_data.head()

   id           purch_date  customer_num  product_num  amount     paid
0   1  2019-01-03 00:00:00           823           27      12  $568.92
1   2  2019-01-03 00:00:00           606           28      14  $395.36
2   3  2019-01-03 00:00:00           955            9      17  $510.17
3   4  2019-01-03 00:00:00           577           19       3   $68.49
4   5  2019-01-03 00:00:00           429            8      18  $759.42

concat -> to manipulation and combine multiple dataframes in pandas

In [ ]:
# If axis = 0 [default] -> rows wise concatinations
# If axis = 1 -> column wise concatinations


combined_df = pd.concat([customers_data, products_data, purchases_data])
combined_df.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,product,cost,company,purch_date,customer_num,product_num,amount,paid
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
combined_df.shape

(7060, 19)

In [ ]:
combined_df1 = pd.concat([customers_data, products_data, purchases_data], axis=1)
combined_df1.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,...,id,product,cost,company,id,purch_date,customer_num,product_num,amount,paid
0,1.0,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,...,1.0,Liners - Baking Cups,$6.36,Skipfire,1,2019-01-03 00:00:00,823,27,12,$568.92
1,2.0,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,...,2.0,Nori Sea Weed - Gold Label,$85.74,Dynazzy,2,2019-01-03 00:00:00,606,28,14,$395.36
2,3.0,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,...,3.0,Bar Bran Honey Nut,$65.40,Ntag,3,2019-01-03 00:00:00,955,9,17,$510.17
3,4.0,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,...,4.0,Soup - Campbells Beef Stew,$68.16,Photojam,4,2019-01-03 00:00:00,577,19,3,$68.49
4,5.0,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,...,5.0,Wine - Shiraz Wolf Blass Premium,$87.39,Eare,5,2019-01-03 00:00:00,429,8,18,$759.42

In [ ]:
combined_df1.shape

(6000, 21)

Inner join only merge common element/id

In [ ]:
merged_df = pd.merge(customers_data, purchases_data, on='id', how='inner')
merged_df

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,purch_date,customer_num,product_num,amount,paid
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,2019-01-03 00:00:00,823,27,12,$568.92
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,2019-01-03 00:00:00,606,28,14,$395.36
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,2019-01-03 00:00:00,955,9,17,$510.17
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,2019-01-03 00:00:00,577,19,3,$68.49
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,2019-01-03 00:00:00,429,8,18,$759.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0,2019-06-04 00:00:00,198,20,7,$609.35
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0,2019-06-04 00:00:00,96,27,14,$663.74
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,2019-06-04 00:00:00,181,7,2,$27.66
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,2019-06-04 00:00:00,951,54,4,$87.68
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,2019-06-04 00:00:00,435,20,18,"$1,143.90"

Left join merges the left side element and the common element

In [ ]:
merged_df_left = pd.merge(customers_data, purchases_data, on='id', how='left')
merged_df_left

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,purch_date,customer_num,product_num,amount,paid
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,2019-01-03 00:00:00,823,27,12,$568.92
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,2019-01-03 00:00:00,606,28,14,$395.36
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,2019-01-03 00:00:00,955,9,17,$510.17
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,2019-01-03 00:00:00,577,19,3,$68.49
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,2019-01-03 00:00:00,429,8,18,$759.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0,2019-06-04 00:00:00,198,20,7,$609.35
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0,2019-06-04 00:00:00,96,27,14,$663.74
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0,2019-06-04 00:00:00,181,7,2,$27.66
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0,2019-06-04 00:00:00,951,54,4,$87.68
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0,2019-06-04 00:00:00,435,20,18,"$1,143.90"

Left join merges the right side element and the common element

In [ ]:
merged_df_right = pd.merge(customers_data, purchases_data, on='id', how='right')
merged_df_right

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode,purch_date,customer_num,product_num,amount,paid
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0,2019-01-03 00:00:00,823,27,12,$568.92
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN,2019-01-03 00:00:00,606,28,14,$395.36
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0,2019-01-03 00:00:00,955,9,17,$510.17
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0,2019-01-03 00:00:00,577,19,3,$68.49
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0,2019-01-03 00:00:00,429,8,18,$759.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,5996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06/20/2019,893,33,5,$411.10
5996,5997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06/20/2019,566,23,11,$178.97
5997,5998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06/20/2019,114,19,9,$205.47
5998,5999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06/20/2019,404,11,20,$429.40
5999,6000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,06/20/2019,88,57,4,$274.52

In [ ]:
data1_customers = pd.DataFrame({
    'id': [ 1, 2, 3],
    'name': ['alice', 'bob', 'charlie'],
    'product': ['book', 'pen', 'notebook']
})
data2_purchase = pd.DataFrame({
    'id': [2, 3, 4],
    'product': ['pen', 'notebook', 'pencil'],
    'amount': [10, 5, 15]
})

In [ ]:
merged_df = pd.merge(data1_customers, data2_purchase, on='id', how='inner')
merged_df

   id     name product_x product_y  amount
0   2      bob       pen       pen      10
1   3  charlie  notebook  notebook       5

In [ ]:
merged_df = pd.merge(data1_customers, data2_purchase, on='id', how='inner', suffixes=('_cust', '_pur')) # We can change (product_x	product_y) using suffixes
merged_df

   id     name product_cust product_pur  amount
0   2      bob          pen         pen      10
1   3  charlie     notebook    notebook       5

In [ ]:
merged_df_left = pd.merge(data1_customers, data2_purchase, on='id', how='left')
merged_df_left

   id     name product_x product_y  amount
0   1    alice      book       NaN     NaN
1   2      bob       pen       pen    10.0
2   3  charlie  notebook  notebook     5.0

In [ ]:
merged_df_right = pd.merge(data1_customers, data2_purchase, on='id', how='right')
merged_df_right

   id     name product_x product_y  amount
0   2      bob       pen       pen      10
1   3  charlie  notebook  notebook       5
2   4      NaN       NaN    pencil      15

In [ ]:
combined_df = pd.concat([data1_customers, data2_purchase])
combined_df

   id     name   product  amount
0   1    alice      book     NaN
1   2      bob       pen     NaN
2   3  charlie  notebook     NaN
0   2      NaN       pen    10.0
1   3      NaN  notebook     5.0
2   4      NaN    pencil    15.0

In [ ]:
combined_df = pd.concat([data1_customers, data2_purchase], axis=1)
combined_df

   id     name   product  id   product  amount
0   1    alice      book   2       pen      10
1   2      bob       pen   3  notebook       5
2   3  charlie  notebook   4    pencil      15

In [ ]:
customers_data.isnull().sum()

id                 0
first_name         0
last_name          0
email            122
gender            43
street_num       262
street_name       37
street_suffix     37
city              79
state             80
postcode         157
dtype: int64

In [ ]:
products_data.isnull().sum()

id         0
product    0
cost       0
company    5
dtype: int64

In [ ]:
purchases_data.isnull().sum()

id              0
purch_date      0
customer_num    0
product_num     0
amount          0
paid            0
dtype: int64

In [ ]:
customers_copy = customers_data.copy()
customers_copy

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

dropna() -> use only when we have a very small proportion of the missing data. Otherwise, we avoide the strategy because that leads to the loss of informations.

In [ ]:
customers_copy = customers_copy.dropna()    # Its drop all the null value
customers_copy

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
5,6,Magdalena,Cullip,mcullip5@tiny.cc,Female,9190.0,Packers,Drive,Baltimore,Maryland,21229.0
6,7,Marietta,Heball,mheball6@blog.com,Female,12.0,Mallory,Center,Carol Stream,Illinois,60351.0
...,...,...,...,...,...,...,...,...,...,...,...
988,989,Vivianne,Abbyss,vabbyssrg@squarespace.com,Female,53592.0,Larry,Road,Santa Cruz,California,95064.0
992,993,Johnath,Clancy,jclancyrk@smugmug.com,Female,7.0,Washington,Crossing,Juneau,Alaska,99812.0
994,995,Brana,Dixon,bdixonrm@myspace.com,Female,97.0,Truax,Avenue,Maple Plain,Minnesota,55572.0
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0

In [ ]:
customers_copy.isnull().sum()

id               0
first_name       0
last_name        0
email            0
gender           0
street_num       0
street_name      0
street_suffix    0
city             0
state            0
postcode         0
dtype: int64

Imputation: With the measure of the central tandency [ mean, median, mode ]

How can we deal with the categorical data. -> Mode

In [ ]:
mode_gender = customers_data['gender'].mode()[0]  #we use [0] cuz incase if there is a balance data so it gives one that one result
mode_gender

'Male'

In [ ]:
customers_data['gender'].fillna(mode_gender, inplace=True)    # Its place 'Male' on missing gender data
customers_data.isnull().sum()

id                 0
first_name         0
last_name          0
email            122
gender             0
street_num       262
street_name       37
street_suffix     37
city              79
state             80
postcode         157
dtype: int64

How can we deal with the numeric data -> ffill(), befill(), mean, median

In [ ]:
customers_data['street_num'].fillna(method='ffill', inplace=True)   #ffill means forward fill
customers_data.isnull().sum()

/tmp/ipython-input-40-3548726039.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers_data['street_num'].fillna(method='ffill', inplace=True)
/tmp/ipython-input-40-3548726039.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  customers_data['street_num'].fillna(method='ffill', inplace=True)

id                 0
first_name         0
last_name          0
email            122
gender             0
street_num         0
street_name       37
street_suffix     37
city              79
state             80
postcode         157
dtype: int64

In [ ]:
customers_data.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,1.0,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,74.0,2nd,Drive,NaN,NaN,83732.0

In [ ]:
customers_data['street_name'].fillna(method='ffill', inplace=True)
customers_data.isnull().sum()

/tmp/ipython-input-43-1714907671.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers_data['street_name'].fillna(method='ffill', inplace=True)
/tmp/ipython-input-43-1714907671.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  customers_data['street_name'].fillna(method='ffill', inplace=True)

id                 0
first_name         0
last_name          0
email            122
gender             0
street_num         0
street_name        0
street_suffix     37
city              79
state             80
postcode         157
dtype: int64

In [ ]:
customers_data['street_suffix'].fillna(method='ffill', inplace=True)
customers_data.isnull().sum()

/tmp/ipython-input-44-3745033828.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers_data['street_suffix'].fillna(method='ffill', inplace=True)
/tmp/ipython-input-44-3745033828.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  customers_data['street_suffix'].fillna(method='ffill', inplace=True)

id                 0
first_name         0
last_name          0
email            122
gender             0
street_num         0
street_name        0
street_suffix      0
city              79
state             80
postcode         157
dtype: int64

In [ ]:
customers_data.head(40)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,1.0,Trailsway,Road,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,74.0,2nd,Drive,NaN,NaN,83732.0
5,6,Magdalena,Cullip,mcullip5@tiny.cc,Female,9190.0,Packers,Drive,Baltimore,Maryland,21229.0
6,7,Marietta,Heball,mheball6@blog.com,Female,12.0,Mallory,Center,Carol Stream,Illinois,60351.0
7,8,Tine,McSperrin,tmcsperrin7@statcounter.com,Male,530.0,Erie,Plaza,Kansas City,Missouri,64193.0
8,9,Enrichetta,de Villier,edevillier8@ox.ac.uk,Female,745.0,Annamark,Street,Fairbanks,Alaska,99709.0
9,10,Sari,Poulden,spoulden9@xing.com,Female,2.0,Pond,Hill,New Orleans,Louisiana,NaN
10,11,Natale,Martina,nmartinaa@wordpress.com,Male,221.0,Sauthoff,Pass,Bradenton,Florida,34205.0
11,12,Noni,Norrington,nnorringtonb@netvibes.com,Female,5.0,Sauthoff,Pass,Baltimore,Maryland,21282.0
12,13,Mikol,MacWhan,mmacwhanc@patch.com,Male,9.0,Eagle Crest,Center,Bronx,New York,10469.0
13,14,Deny,Thraves,dthravesd@ibm.com,Female,71865.0,Valley Edge,Place,Washington,District of Columbia,20456.0
14,15,Fara,Petegrew,fpetegrewe@ebay.com,Female,71865.0,Claremont,Place,Los Angeles,California,90005.0
15,16,Jodie,De Cristoforo,jdecristoforof@mac.com,Male,50948.0,Rowland,Alley,Charleston,South Carolina,29424.0
16,17,Tobi,Dewicke,tdewickeg@hostgator.com,Female,6817.0,Orin,Junction,San Rafael,NaN,NaN
17,18,Reinhold,Woolforde,rwoolfordeh@cbc.ca,Male,6817.0,Northwestern,Way,Amarillo,Texas,79118.0
18,19,Fredek,Foley,ffoleyi@bbb.org,Male,8.0,Ridgeway,Park,Silver Spring,Maryland,20910.0
19,20,Rubina,Hustings,rhustingsj@wikimedia.org,Female,249.0,Esker,Hill,San Antonio,Texas,78210.0
20,21,Karim,Woosnam,kwoosnamk@ifeng.com,Male,249.0,Grayhawk,Place,Houston,Texas,NaN
21,22,Woodrow,Fidoe,wfidoel@creativecommons.org,Male,1.0,Artisan,Junction,Gainesville,NaN,NaN
22,23,Loralie,Normand,lnormandm@usa.gov,Female,1.0,Transport,Terrace,Duluth,NaN,30195.0
23,24,Danita,Cleynaert,dcleynaertn@t-online.de,Female,1.0,Shopko,Center,Denton,Texas,76205.0
24,25,Tomlin,Massinger,NaN,Male,9.0,Victoria,Trail,Washington,District of Columbia,20409.0
25,26,Franklin,Goodge,fgoodgep@mapquest.com,Male,97670.0,Kensington,Center,Houston,Texas,77240.0
26,27,Harlene,Rameau,hrameauq@squarespace.com,Female,2352.0,American,Way,Seattle,Washington,98127.0
27,28,Brander,Quinnelly,bquinnellyr@shinystat.com,Male,573.0,Dovetail,Center,Sparks,Nevada,89436.0
28,29,Jeanna,Bruntje,jbruntjes@tuttocitta.it,Female,9296.0,Hanover,Road,Fort Wayne,Indiana,46814.0
29,30,Ardyth,Zack,azackt@wordpress.com,Female,437.0,Pierstorff,Way,Pittsburgh,Pennsylvania,NaN
30,31,Steve,Pantridge,NaN,Male,6124.0,Kropf,Street,Los Angeles,California,90065.0
31,32,Brit,Nouch,bnouchv@yahoo.com,Female,2385.0,Blaine,Trail,Augusta,Georgia,NaN
32,33,Caril,Barnsley,cbarnsleyw@bravesites.com,Female,2385.0,Mallory,Way,Fort Wayne,Indiana,46896.0
33,34,Rosalynd,Dyerson,rdyersonx@geocities.jp,Female,2385.0,Cody,Court,Dallas,Texas,75226.0
34,35,Griffy,Sonley,gsonleyy@deviantart.com,Male,1.0,Cody,Court,NaN,Virginia,22070.0
35,36,Ernest,Armal,earmalz@dailymail.co.uk,Male,4.0,Susan,Center,Washington,District of Columbia,20231.0
36,37,Elspeth,Mendus,emendus10@ocn.ne.jp,Female,127.0,Mockingbird,Hill,Washington,District of Columbia,NaN
37,38,Clarita,Bussons,cbussons11@marketwatch.com,Female,7444.0,Northwestern,Crossing,Lansing,Michigan,48912.0
38,39,Stanislas,Hacaud,NaN,Male,76.0,Summer Ridge,Place,Atlanta,Georgia,31119.0
39,40,Melvyn,Seifert,mseifert13@photobucket.com,Male,76.0,Park Meadow,Pass,San Antonio,Texas,78260.0

In [ ]:
customers_data['city'].fillna(method='bfill', inplace=True)
customers_data['state'].fillna(method='bfill', inplace=True)
customers_data['postcode'].fillna(method='bfill', inplace=True)
customers_data.isnull().sum()

/tmp/ipython-input-49-2653208470.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  customers_data['city'].fillna(method='bfill', inplace=True)
/tmp/ipython-input-49-2653208470.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers_data['state'].fillna(method='bfill', inplace=True)
/tmp/ipython-input-49-2653208470.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  customers_data['state'].fillna(method='bfill', inplace=True)
/tmp/ipython-input-49-2653208470.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers_data['postcode'].fillna(method='bfill', inplace=True)
/tmp/ipython-input-49-2653208470.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  customers_data['postcode'].fillna(method='bfill', inplace=True)

id                 0
first_name         0
last_name          0
email            122
gender             0
street_num         0
street_name        0
street_suffix      0
city               0
state              0
postcode           0
dtype: int64

In [ ]:
customers_data.head(40
)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,1.0,Trailsway,Road,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,74.0,2nd,Drive,Baltimore,NaN,83732.0
5,6,Magdalena,Cullip,mcullip5@tiny.cc,Female,9190.0,Packers,Drive,Baltimore,Maryland,21229.0
6,7,Marietta,Heball,mheball6@blog.com,Female,12.0,Mallory,Center,Carol Stream,Illinois,60351.0
7,8,Tine,McSperrin,tmcsperrin7@statcounter.com,Male,530.0,Erie,Plaza,Kansas City,Missouri,64193.0
8,9,Enrichetta,de Villier,edevillier8@ox.ac.uk,Female,745.0,Annamark,Street,Fairbanks,Alaska,99709.0
9,10,Sari,Poulden,spoulden9@xing.com,Female,2.0,Pond,Hill,New Orleans,Louisiana,NaN
10,11,Natale,Martina,nmartinaa@wordpress.com,Male,221.0,Sauthoff,Pass,Bradenton,Florida,34205.0
11,12,Noni,Norrington,nnorringtonb@netvibes.com,Female,5.0,Sauthoff,Pass,Baltimore,Maryland,21282.0
12,13,Mikol,MacWhan,mmacwhanc@patch.com,Male,9.0,Eagle Crest,Center,Bronx,New York,10469.0
13,14,Deny,Thraves,dthravesd@ibm.com,Female,71865.0,Valley Edge,Place,Washington,District of Columbia,20456.0
14,15,Fara,Petegrew,fpetegrewe@ebay.com,Female,71865.0,Claremont,Place,Los Angeles,California,90005.0
15,16,Jodie,De Cristoforo,jdecristoforof@mac.com,Male,50948.0,Rowland,Alley,Charleston,South Carolina,29424.0
16,17,Tobi,Dewicke,tdewickeg@hostgator.com,Female,6817.0,Orin,Junction,San Rafael,NaN,NaN
17,18,Reinhold,Woolforde,rwoolfordeh@cbc.ca,Male,6817.0,Northwestern,Way,Amarillo,Texas,79118.0
18,19,Fredek,Foley,ffoleyi@bbb.org,Male,8.0,Ridgeway,Park,Silver Spring,Maryland,20910.0
19,20,Rubina,Hustings,rhustingsj@wikimedia.org,Female,249.0,Esker,Hill,San Antonio,Texas,78210.0
20,21,Karim,Woosnam,kwoosnamk@ifeng.com,Male,249.0,Grayhawk,Place,Houston,Texas,NaN
21,22,Woodrow,Fidoe,wfidoel@creativecommons.org,Male,1.0,Artisan,Junction,Gainesville,NaN,NaN
22,23,Loralie,Normand,lnormandm@usa.gov,Female,1.0,Transport,Terrace,Duluth,NaN,30195.0
23,24,Danita,Cleynaert,dcleynaertn@t-online.de,Female,1.0,Shopko,Center,Denton,Texas,76205.0
24,25,Tomlin,Massinger,NaN,Male,9.0,Victoria,Trail,Washington,District of Columbia,20409.0
25,26,Franklin,Goodge,fgoodgep@mapquest.com,Male,97670.0,Kensington,Center,Houston,Texas,77240.0
26,27,Harlene,Rameau,hrameauq@squarespace.com,Female,2352.0,American,Way,Seattle,Washington,98127.0
27,28,Brander,Quinnelly,bquinnellyr@shinystat.com,Male,573.0,Dovetail,Center,Sparks,Nevada,89436.0
28,29,Jeanna,Bruntje,jbruntjes@tuttocitta.it,Female,9296.0,Hanover,Road,Fort Wayne,Indiana,46814.0
29,30,Ardyth,Zack,azackt@wordpress.com,Female,437.0,Pierstorff,Way,Pittsburgh,Pennsylvania,NaN
30,31,Steve,Pantridge,NaN,Male,6124.0,Kropf,Street,Los Angeles,California,90065.0
31,32,Brit,Nouch,bnouchv@yahoo.com,Female,2385.0,Blaine,Trail,Augusta,Georgia,NaN
32,33,Caril,Barnsley,cbarnsleyw@bravesites.com,Female,2385.0,Mallory,Way,Fort Wayne,Indiana,46896.0
33,34,Rosalynd,Dyerson,rdyersonx@geocities.jp,Female,2385.0,Cody,Court,Dallas,Texas,75226.0
34,35,Griffy,Sonley,gsonleyy@deviantart.com,Male,1.0,Cody,Court,Washington,Virginia,22070.0
35,36,Ernest,Armal,earmalz@dailymail.co.uk,Male,4.0,Susan,Center,Washington,District of Columbia,20231.0
36,37,Elspeth,Mendus,emendus10@ocn.ne.jp,Female,127.0,Mockingbird,Hill,Washington,District of Columbia,NaN
37,38,Clarita,Bussons,cbussons11@marketwatch.com,Female,7444.0,Northwestern,Crossing,Lansing,Michigan,48912.0
38,39,Stanislas,Hacaud,NaN,Male,76.0,Summer Ridge,Place,Atlanta,Georgia,31119.0
39,40,Melvyn,Seifert,mseifert13@photobucket.com,Male,76.0,Park Meadow,Pass,San Antonio,Texas,78260.0

In [ ]:
customers_data['email'].fillna('Unknown', inplace=True)
customers_data.isnull().sum()

/tmp/ipython-input-50-3733209587.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  customers_data['email'].fillna('Unknown', inplace=True)

id               0
first_name       0
last_name        0
email            0
gender           0
street_num       0
street_name      0
street_suffix    0
city             0
state            0
postcode         0
dtype: int64

In [ ]:
customers_data.head(50)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,1.0,Trailsway,Road,El Paso,Texas,78220.0
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,Male,74.0,2nd,Drive,Baltimore,Maryland,83732.0
5,6,Magdalena,Cullip,mcullip5@tiny.cc,Female,9190.0,Packers,Drive,Baltimore,Maryland,21229.0
6,7,Marietta,Heball,mheball6@blog.com,Female,12.0,Mallory,Center,Carol Stream,Illinois,60351.0
7,8,Tine,McSperrin,tmcsperrin7@statcounter.com,Male,530.0,Erie,Plaza,Kansas City,Missouri,64193.0
8,9,Enrichetta,de Villier,edevillier8@ox.ac.uk,Female,745.0,Annamark,Street,Fairbanks,Alaska,99709.0
9,10,Sari,Poulden,spoulden9@xing.com,Female,2.0,Pond,Hill,New Orleans,Louisiana,34205.0
10,11,Natale,Martina,nmartinaa@wordpress.com,Male,221.0,Sauthoff,Pass,Bradenton,Florida,34205.0
11,12,Noni,Norrington,nnorringtonb@netvibes.com,Female,5.0,Sauthoff,Pass,Baltimore,Maryland,21282.0
12,13,Mikol,MacWhan,mmacwhanc@patch.com,Male,9.0,Eagle Crest,Center,Bronx,New York,10469.0
13,14,Deny,Thraves,dthravesd@ibm.com,Female,71865.0,Valley Edge,Place,Washington,District of Columbia,20456.0
14,15,Fara,Petegrew,fpetegrewe@ebay.com,Female,71865.0,Claremont,Place,Los Angeles,California,90005.0
15,16,Jodie,De Cristoforo,jdecristoforof@mac.com,Male,50948.0,Rowland,Alley,Charleston,South Carolina,29424.0
16,17,Tobi,Dewicke,tdewickeg@hostgator.com,Female,6817.0,Orin,Junction,San Rafael,Texas,79118.0
17,18,Reinhold,Woolforde,rwoolfordeh@cbc.ca,Male,6817.0,Northwestern,Way,Amarillo,Texas,79118.0
18,19,Fredek,Foley,ffoleyi@bbb.org,Male,8.0,Ridgeway,Park,Silver Spring,Maryland,20910.0
19,20,Rubina,Hustings,rhustingsj@wikimedia.org,Female,249.0,Esker,Hill,San Antonio,Texas,78210.0
20,21,Karim,Woosnam,kwoosnamk@ifeng.com,Male,249.0,Grayhawk,Place,Houston,Texas,30195.0
21,22,Woodrow,Fidoe,wfidoel@creativecommons.org,Male,1.0,Artisan,Junction,Gainesville,Texas,30195.0
22,23,Loralie,Normand,lnormandm@usa.gov,Female,1.0,Transport,Terrace,Duluth,Texas,30195.0
23,24,Danita,Cleynaert,dcleynaertn@t-online.de,Female,1.0,Shopko,Center,Denton,Texas,76205.0
24,25,Tomlin,Massinger,Unknown,Male,9.0,Victoria,Trail,Washington,District of Columbia,20409.0
25,26,Franklin,Goodge,fgoodgep@mapquest.com,Male,97670.0,Kensington,Center,Houston,Texas,77240.0
26,27,Harlene,Rameau,hrameauq@squarespace.com,Female,2352.0,American,Way,Seattle,Washington,98127.0
27,28,Brander,Quinnelly,bquinnellyr@shinystat.com,Male,573.0,Dovetail,Center,Sparks,Nevada,89436.0
28,29,Jeanna,Bruntje,jbruntjes@tuttocitta.it,Female,9296.0,Hanover,Road,Fort Wayne,Indiana,46814.0
29,30,Ardyth,Zack,azackt@wordpress.com,Female,437.0,Pierstorff,Way,Pittsburgh,Pennsylvania,90065.0
30,31,Steve,Pantridge,Unknown,Male,6124.0,Kropf,Street,Los Angeles,California,90065.0
31,32,Brit,Nouch,bnouchv@yahoo.com,Female,2385.0,Blaine,Trail,Augusta,Georgia,46896.0
32,33,Caril,Barnsley,cbarnsleyw@bravesites.com,Female,2385.0,Mallory,Way,Fort Wayne,Indiana,46896.0
33,34,Rosalynd,Dyerson,rdyersonx@geocities.jp,Female,2385.0,Cody,Court,Dallas,Texas,75226.0
34,35,Griffy,Sonley,gsonleyy@deviantart.com,Male,1.0,Cody,Court,Washington,Virginia,22070.0
35,36,Ernest,Armal,earmalz@dailymail.co.uk,Male,4.0,Susan,Center,Washington,District of Columbia,20231.0
36,37,Elspeth,Mendus,emendus10@ocn.ne.jp,Female,127.0,Mockingbird,Hill,Washington,District of Columbia,48912.0
37,38,Clarita,Bussons,cbussons11@marketwatch.com,Female,7444.0,Northwestern,Crossing,Lansing,Michigan,48912.0
38,39,Stanislas,Hacaud,Unknown,Male,76.0,Summer Ridge,Place,Atlanta,Georgia,31119.0
39,40,Melvyn,Seifert,mseifert13@photobucket.com,Male,76.0,Park Meadow,Pass,San Antonio,Texas,78260.0
40,41,Ruby,Plott,rplott14@un.org,Male,2.0,Killdeer,Pass,Seattle,Washington,98121.0
41,42,Nollie,Salter,nsalter15@fastcompany.com,Male,23.0,Lake View,Point,Irving,Tennessee,38150.0
42,43,Bendicty,Sunnex,bsunnex16@elpais.com,Male,39695.0,North,Place,Irving,Texas,77070.0
43,44,Garrett,Bartram,gbartram17@sun.com,Male,15.0,Everett,Way,Houston,Texas,77070.0
44,45,Berna,Longhurst,blonghurst18@geocities.jp,Female,50870.0,Milwaukee,Hill,El Paso,Texas,79916.0
45,46,Edmon,Elsegood,eelsegood19@ezinearticles.com,Male,48085.0,Pepper Wood,Street,Des Moines,Iowa,50362.0
46,47,Burch,Issacov,bissacov1a@tiny.cc,Male,54399.0,Pepper Wood,Street,Dallas,Texas,75397.0
47,48,Rori,Clashe,rclashe1b@smh.com.au,Female,558.0,Rigney,Avenue,Everett,Washington,98206.0
48,49,Flinn,Hoston,Unknown,Male,84.0,Waxwing,Terrace,Washington,District of Columbia,20530.0
49,50,Claudette,Ivatts,Unknown,Female,5552.0,Bunting,Junction,San Francisco,California,94137.0

In [ ]:
products_data.isnull().sum()

id         0
product    0
cost       0
company    5
dtype: int64

In [ ]:
products_data['company'].fillna('Unknown', inplace=True)

/tmp/ipython-input-55-2097552700.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  products_data['company'].fillna('Unknown', inplace=True)

In [ ]:
products_data.isnull().sum()

id         0
product    0
cost       0
company    0
dtype: int64

In [ ]:
purchases_data['paid'] = purchases_data['paid'].str.replace('[\$,]', '', regex=True)

In [ ]:
purchases_data['paid'] = purchases_data['paid'].astype(float)

In [ ]:
purchases_data['purch_date'] = pd.to_datetime(purchases_data['purch_date'])
purchases_data.dtypes

id                       int64
purch_date      datetime64[ns]
customer_num             int64
product_num              int64
amount                   int64
paid                   float64
dtype: object

# Data Analysis: Aggregation

Group by 'customer_num' and compute the sum of 'amount' and 'paid' coulmn

In [ ]:
aggregated_purchase = purchases_data.groupby('customer_num').agg({'amount': 'sum', 'paid': 'sum'})
aggregated_purchase

              amount     paid
customer_num
1                 24   779.34
2                 67  3978.09
3                 88  5031.39
4                 38  2276.38
5                 46  2931.24
...              ...      ...
996               31  2339.19
997               55  3030.34
998               69  3346.93
999               66  3640.48
1000              75  3961.63

[997 rows x 2 columns]

In [ ]:
aggregated_purchase_date = purchases_data.groupby('purch_date').agg({'amount': 'sum', 'paid': 'sum'})

In [ ]:
aggregated_purchase_date

            amount      paid
purch_date
2019-01-03     480  20468.33
2019-01-04     872  48529.13
2019-01-05     715  38643.67
2019-01-06     576  32345.29
2019-02-03     568  28183.50
...            ...       ...
2019-11-06     475  24778.05
2019-12-03     524  27691.62
2019-12-04     647  37100.59
2019-12-05     380  20845.55
2019-12-06     481  26410.08

[108 rows x 2 columns]