<a href="https://colab.research.google.com/github/SinghAbh1shek/Pandas/blob/main/Pandas_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_excel('/content/customers_lyst1748071473851.xlsx')
data.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             1000 non-null   int64
 1   first_name     1000 non-null   object
 2   last_name      1000 non-null   object
 3   email          878 non-null    object
 4   gender         957 non-null    object
 5   street_num     738 non-null    float64
 6   street_name    963 non-null    object
 7   street_suffix  963 non-null    object
 8   city           921 non-null    object
 9   state          920 non-null    object
 10  postcode       843 non-null    float64
dtypes: float64(2), int64(1), object(8)
memory usage: 86.1+ KB

Add a new column named as 'Country' and the value inside that is 'USA' in the above dataframe

In [ ]:
data['country'] = 'USA'

In [ ]:
data.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

Task: I want to place the 'country' coulmn after the 'city' coulmn

In [ ]:
data.insert(9, 'country', 'USA')

In [ ]:
data.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,country,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,USA,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,USA,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,USA,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,USA,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,USA,NaN,83732.0

Create a new column "FullName" which is composed of firstName and lastName

In [ ]:
data.insert(3, 'full_name', data['first_name']+ " "  +data['last_name'])

In [ ]:
data.head()

,id,first_name,last_name,full_name,email,gender,street_num,street_name,street_suffix,city,country,state,postcode
0,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,USA,California,92127.0
1,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,USA,Texas,NaN
2,3,Bambi,Westrip,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,USA,Texas,78220.0
3,4,Roarke,Pankettman,Roarke Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,USA,Tennessee,38150.0
4,5,Mikaela,Althorpe,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,USA,NaN,83732.0

Access the rows in a given dataframe:.loc(), .iloc()

In [ ]:
dataframe = {
    'name': ['Arun', 'Amit', 'Anuj', 'Anup', 'Aman'],
    'Age':[22, 20, 24, 31, 21],
    'city': ['Jaipur', 'Bhopal', 'Patna', 'Punjab', 'Siwan']
}

dataframe = pd.DataFrame(dataframe, index = ['a', 'b', 'c', 'd', 'e'])
dataframe

   name  Age    city
a  Arun   22  Jaipur
b  Amit   20  Bhopal
c  Anuj   24   Patna
d  Anup   31  Punjab
e  Aman   21   Siwan

.loc only works on customized index
and the last element is inclusive

In [ ]:
dataframe.loc['b']

name      Amit
Age         20
city    Bhopal
Name: b, dtype: object

In [ ]:
dataframe.loc['b':'d']

   name  Age    city
b  Amit   20  Bhopal
c  Anuj   24   Patna
d  Anup   31  Punjab

.iloc only works on default indexing
and the last element is exclusive while slicing

In [ ]:
dataframe.iloc[1:4]

   name  Age    city
b  Amit   20  Bhopal
c  Anuj   24   Patna
d  Anup   31  Punjab

In [ ]:
dataframe_v1 = {
    'name': ['Arun', 'Amit', 'Anuj', 'Anup', 'Aman'],
    'Age':[22, 20, 24, 31, 21],
    'city': ['Jaipur', 'Bhopal', 'Patna', 'Punjab', 'Siwan']
}

dataframe_v1 = pd.DataFrame(dataframe_v1)
dataframe_v1

   name  Age    city
0  Arun   22  Jaipur
1  Amit   20  Bhopal
2  Anuj   24   Patna
3  Anup   31  Punjab
4  Aman   21   Siwan

In [ ]:
dataframe_v1.loc[3]   # In this case loc works same as iloc cuz here default and custimized indexing are same

name      Anup
Age         31
city    Punjab
Name: 3, dtype: object

In [ ]:
dataframe_v1.iloc[3]

name      Anup
Age         31
city    Punjab
Name: 3, dtype: object

In [ ]:
data

,id,first_name,last_name,full_name,email,gender,street_num,street_name,street_suffix,city,country,state,postcode
0,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,USA,California,92127.0
1,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,USA,Texas,NaN
2,3,Bambi,Westrip,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,USA,Texas,78220.0
3,4,Roarke,Pankettman,Roarke Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,USA,Tennessee,38150.0
4,5,Mikaela,Althorpe,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,USA,NaN,83732.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,Merrili Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,USA,Pennsylvania,19610.0
996,997,Winonah,Heckle,Winonah Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,USA,Indiana,46278.0
997,998,Tobit,Birt,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,USA,Connecticut,6721.0
998,999,Issiah,Standbrooke,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,USA,Georgia,31405.0
999,1000,Elmore,Malpas,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,USA,Georgia,30386.0

In [ ]:
data.shape

(1000, 13)

access the details of the id's of the customer from 5000 to 5004

In [ ]:
data.loc[500:504]

,id,first_name,last_name,full_name,email,gender,street_num,street_name,street_suffix,country,city,state,postcode
500,501,Elliot,Polycote,Elliot Polycote,epolycotedw@infoseek.co.jp,Male,NaN,Prentice,Drive,USA,Hartford,Connecticut,NaN
501,502,Shirline,Halpin,Shirline Halpin,shalpindx@moonfruit.com,NaN,76640.0,Buell,Circle,USA,Dallas,Texas,75216.0
502,503,Darcy,Cruddace,Darcy Cruddace,NaN,NaN,NaN,Ridgeview,Court,USA,Utica,New York,13505.0
503,504,Toiboid,Bentzen,Toiboid Bentzen,tbentzendz@freewebs.com,Male,913.0,2nd,Trail,USA,White Plains,New York,10606.0
504,505,Paxon,Corris,Paxon Corris,pcorrise0@behance.net,Male,8362.0,Eliot,Way,USA,Des Moines,Iowa,50362.0

In [ ]:
data[(data['id'] >= 500) & (data['id'] <= 504)]

,id,first_name,last_name,full_name,email,gender,street_num,street_name,street_suffix,city,country,state,postcode
499,500,Carolann,Balcock,Carolann Balcock,cbalcockdv@alexa.com,Female,NaN,Stone Corner,Pass,El Paso,USA,Texas,79916.0
500,501,Elliot,Polycote,Elliot Polycote,epolycotedw@infoseek.co.jp,Male,NaN,Prentice,Drive,Hartford,USA,Connecticut,NaN
501,502,Shirline,Halpin,Shirline Halpin,shalpindx@moonfruit.com,NaN,76640.0,Buell,Circle,Dallas,USA,Texas,75216.0
502,503,Darcy,Cruddace,Darcy Cruddace,NaN,NaN,NaN,Ridgeview,Court,Utica,USA,New York,13505.0
503,504,Toiboid,Bentzen,Toiboid Bentzen,tbentzendz@freewebs.com,Male,913.0,2nd,Trail,White Plains,USA,New York,10606.0

In [ ]:
data.pop('country')

0      USA
1      USA
2      USA
3      USA
4      USA
      ...
995    USA
996    USA
997    USA
998    USA
999    USA
Name: country, Length: 1000, dtype: object

In [ ]:
data.drop(columns="country")  # It create the new dataframe

,id,first_name,last_name,full_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,Roarke Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,Merrili Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,Winonah Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

In [ ]:
data

,id,first_name,last_name,full_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,Roarke Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,Merrili Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,Winonah Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

In [ ]:
# data = data.drop(columns='country')
data.drop(columns='country', inplace=True)   #We can also write like this

rename the row index with the custom index
0 -> firstCustomer
1 -> secondeCustomer

In [ ]:
rename_dict = {
    0: 'firstCustomer',
    1: 'secondCustomer'
}

data.rename(index=rename_dict, inplace=True)  # We use inplace for change in same dataframe
data.head()

,id,first_name,last_name,full_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
firstCustomer,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
secondCustomer,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,Roarke Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0

In [ ]:
data.loc['firstCustomer': 'secondCustomer']

,id,first_name,last_name,full_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
firstCustomer,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
secondCustomer,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN

In [ ]:
data.iloc[0: 2]

,id,first_name,last_name,full_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
firstCustomer,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
secondCustomer,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN

Finding Unique Value

Rename the street_name with street_address and street_num with the street_number

In [ ]:
data.rename(columns={'street_num': 'street_number', 'street_name': 'street_address'})

,id,first_name,last_name,full_name,email,gender,street_number,street_address,street_suffix,city,state,postcode
firstCustomer,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
secondCustomer,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,Roarke Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,Merrili Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,Winonah Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0

In [ ]:
unique_gender = data['gender'].unique()
unique_gender

array(['Male', 'Female', nan], dtype=object)

In [ ]:
num_of_nan = data['gender'].nunique()
num_of_nan

2

In [ ]:
data['gender'].value_counts()

gender
Male      485
Female    472
Name: count, dtype: int64

In [ ]:
data

,id,first_name,last_name,full_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
firstCustomer,1,Romain,Southcott,Romain Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
secondCustomer,2,Cosimo,Molyneaux,Cosimo Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,Bambi Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,Roarke Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,Mikaela Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,Merrili Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,Winonah Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,Tobit Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,Issiah Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,Elmore Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0